version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - '9009:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ${HOME}/voidsync/minio:/data
    command: server /data --console-address ":9090"

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - '8000:8000'
    volumes:
      - ${HOME}/voidsync/surrealdb:/mydata
    command: start --log trace --user root --pass root file:/mydata/mydatabase.db

    # mkdir -p ${HOME}/voidsync/minio
    # mkdir -p ${HOME}/voidsync/surrealdb
    # mkdir -p ${HOME}/voidsync/blog
